server:
  port: 18084
mybatis-plus:
  mapper-locations: classpath:mapper/sms/*.xml  # 读取映射文件
  type-aliases-package: com.atguigu.gmall.sms.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
feign:
  sentinel:
    enabled: true